language: java
sudo: required
services:
  - docker
jdk:
  - oraclejdk8
script:
  - mvn clean package -DskipTests
  - docker build -t lennonsaves/fructa:latest .
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push lennonsaves/fructa:latest

