language: java
sudo: required
services:
- docker
jdk:
- oraclejdk8
script:
- mvn clean package -DskipTests
- docker build -t lennonsaves/fructa:latest .
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push lennonsaves/fructa:latest
deploy:
  provider: script
  script: deploy.sh
before_install:
- openssl aes-256-cbc -K $encrypted_1ef52a92cc44_key -iv $encrypted_1ef52a92cc44_iv
  -in deploy_rsa.enc -out deploy_rsa -d
