server:
  port: 3000
jwt:
  header: Authorization
  secret: abcdef
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
fructa:
  prize: 8
  gateway: "gateway.fructa.ga"